from functools import lru_cache

_vautoTLWToLocaleNames = {
	"ARG": "ar",
	"ARW": "ar",
	"BAE": "eu",
	"BEI": "bn_IN",
	"BGB": "bg",
	"BHI": "bh_IN",
	"CAE": "ca",
	"CAH": "zh_HK",
	"CZC": "cs_CZ",
	"DAD": "da_DK",
	"DOC": "zh_CMN",
	"DUB": "nl_BE",
	"DUN": "nl_NL",
	"ENA": "en_AU",
	"ENE": "en_IE",
	"ENG": "en_GB",
	"ENI": "en_IN",
	"ENS": "en_SC",
	"ENU": "en_US",
	"ENZ": "en_ZA",
	"FAI": "fa_IR",
	"FIF": "fi_FI",
	"FRB": "fr_BE",
	"FRC": "fr_CA",
	"FRF": "fr_FR",
	"GED": "de_DE",
	"GLE": "gl_ES",
	"GRG": "el_GR",
	"HEI": "he_IL",
	"HII": "hi_IN",
	"HRH": "hr_HR",
	"HUH": "hu_HU",
	"IDI": "id_ID",
	"ITI": "it_IT",
	"JPJ": "ja_JP",
	"KAI": "kn_IN",
	"KOK": "ko_KR",
	"MAI": "mr_IN",
	"MNC": "zh_CN",
	"MNT": "zh_TW",
	"MSM": "ms_MS",
	"NON": "nn_NO",
	"PLP": "pl_PL",
	"PTB": "pt_BR",
	"PTP": "pt_PT",
	"ROR": "ro_RO",
	"RUR": "ru_RU",
	"SIC": "ii_CN",
	"SHC": "zh_WUU",
	"SKS": "sk_SK",
	"SLS": "sl_SI",
	"SPA": "es_AR",
	"SPC": "es_CO",
	"SPE": "es_ES",
	"SPL": "es_CH",
	"SPM": "es_MX",
	"SWS": "sv_SE",
	"SXC": "zh_SZY",
	"TAI": "ta_IN",
	"TEI": "te_IN",
	"THT": "th_TH",
	"TRT": "tr_TR",
	"UKU": "uk_UA",
	"VAE": "ca",
	"VIV": "vi_VN",
}

def getLocaleNameFromTLW(tlw):
	return _vautoTLWToLocaleNames.get(tlw, None)


@lru_cache(maxsize=None)
def getTLWFromLocaleName(localeName):
	return {v: k for k, v in _vautoTLWToLocaleNames.items()}.get(localeName, None)
